apiVersion: apps/v1
kind: Deployment
metadata:
  name: miguelsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miguelsub
  template:
    metadata:
      labels:
        app: miguelsub
    spec:
      containers:
      - name: miguelsub
        image: miguelgrigorio27/deploy-kube:latest
        volumeMounts:
        - name: volume-imagens
          mountPath: /app/data  # Caminho dentro do contêiner
        envFrom:
        - configMapRef:
            name: miguel-deploy-kube-config
      volumes:
      - name: volume-imagens
        persistentVolumeClaim:
          claimName: pvc-imagens
