apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-imagens
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/k8s/images  # Caminho no host onde os dados serão armazenados